name: Python pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y 
          sudo apt-get install python3 -y 
          sudo apt-get install python3-pip -y 
          sudo apt-get install python3-venv -y

      - name: Create and use venv
        run: |
          python3 -m venv myenv
          source myenv/bin/activate
          pip install -r requirements.txt
        
      - name: Initialize db.py
        run: |
          source myenv/bin/activate  
          python db.py -a 
        
      - name: Test application
        run: | 
          echo "No tests"